/**
 * Sistema de Gestão Hospital API
 * Documentação da API de acesso aos endpoints da GestaoHospitalAPI - Aceleradev Brasil  Jornada de desafios da Aceleradev Brasil - CodeNation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.gestaohospital.api

import examples.gestaohospital.model.HospitalDTO
import examples.gestaohospital.model.LocationDTO
import examples.gestaohospital.core.JsonSupport._
import sttp.client3._
import sttp.model.Method

object LocationResourceApi {

def apply(baseUrl: String = "http://localhost:8080") = new LocationResourceApi(baseUrl)
}

class LocationResourceApi(baseUrl: String) {

  /**
   * Expected answers:
   *   code 200 : Seq[HospitalDTO] (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * @param hospitalId hospital_id
   * @param raio raio
   */
  def findHospitalNearHospitalByUsingGET(hospitalId: String, raio: Double
): Request[Either[ResponseException[String, Exception], Seq[HospitalDTO]], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/v1/hospitais/${hospitalId}/hospitaisProximos?raio=${ raio }")
      .contentType("application/json")
      .response(asJson[Seq[HospitalDTO]])

  /**
   * Expected answers:
   *   code 200 : Seq[LocationDTO] (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * @param hospitalId hospital_id
   */
  def findLocationNearHospitalByUsingGET(hospitalId: String
): Request[Either[ResponseException[String, Exception], Seq[LocationDTO]], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/v1/hospitais/${hospitalId}/proximidades")
      .contentType("application/json")
      .response(asJson[Seq[LocationDTO]])

}
