/**
 * Sistema de Gestão Hospital API
 * Documentação da API de acesso aos endpoints da GestaoHospitalAPI - Aceleradev Brasil  Jornada de desafios da Aceleradev Brasil - CodeNation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.gestaohospital.model


case class HospitalDTO(
  address: Option[String] = None,
  availableBeds: Option[Int] = None,
  beds: Option[Int] = None,
  id: Option[String] = None,
  latitude: Option[String] = None,
  longitude: Option[String] = None,
  name: Option[String] = None
)

