/**
 * Sistema de Gestão Hospital API
 * Documentação da API de acesso aos endpoints da GestaoHospitalAPI - Aceleradev Brasil  Jornada de desafios da Aceleradev Brasil - CodeNation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.gestaohospital.model


case class Location(
  id: Option[String] = None,
  location: Option[GeoJsonPoint] = None,
  locationCategory: Option[LocationEnums.LocationCategory] = None,
  name: Option[String] = None,
  position: Option[GeoJsonPoint] = None,
  referenceId: Option[String] = None
)

object LocationEnums {

  type LocationCategory = LocationCategory.Value
  object LocationCategory extends Enumeration {
    val HOSPITAL = Value("HOSPITAL")
    val PATIENT = Value("PATIENT")
  }

}
