/**
 * Sistema de Gestão Hospital API
 * Documentação da API de acesso aos endpoints da GestaoHospitalAPI - Aceleradev Brasil  Jornada de desafios da Aceleradev Brasil - CodeNation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.gestaohospital.model


case class ProductDTO(
  description: Option[String] = None,
  id: Option[String] = None,
  name: Option[String] = None,
  productName: Option[String] = None,
  productType: Option[ProductDTOEnums.ProductType] = None,
  quantity: Option[Int] = None
)

object ProductDTOEnums {

  type ProductType = ProductType.Value
  object ProductType extends Enumeration {
    val COMMON = Value("COMMON")
    val BLOOD = Value("BLOOD")
  }

}
