/**
 * cwa-verification-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.cwa.api

import examples.cwa.model.RegistrationToken
import examples.cwa.model.RegistrationTokenRequest
import examples.cwa.core.JsonSupport._
import sttp.client3._
import sttp.model.Method

object ExternalTokenControllerApi {

def apply(baseUrl: String = "http://localhost:8080") = new ExternalTokenControllerApi(baseUrl)
}

class ExternalTokenControllerApi(baseUrl: String) {

  /**
   * Get a registration token by providing a SHA-256 hasehd GUID or a teleTAN
   * 
   * Expected answers:
   *   code 500 :  (Internal Server Error)
   *   code 400 :  (GUID/TeleTAN already exists.)
   *   code 405 :  (Method Not Allowed)
   *   code 415 :  (Unsupported Media Type)
   *   code 201 : RegistrationToken (registration token generated.)
   * 
   * @param registrationTokenRequest 
   * @param cwaFake 
   */
  def generateRegistrationToken(registrationTokenRequest: RegistrationTokenRequest, cwaFake: Option[String] = None
): Request[Either[ResponseException[String, Exception], RegistrationToken], Any] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/version/v1/registrationToken")
      .contentType("application/json")
      .header("cwa-fake", cwaFake.toString)
      .body(registrationTokenRequest)
      .response(asJson[RegistrationToken])

}
