/**
 * cwa-verification-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.cwa.model


  /**
   * The registration token request model.
   */
case class RegistrationTokenRequest(
  key: String,
  keyDob: Option[String] = None,
  keyType: RegistrationTokenRequestEnums.KeyType
)

object RegistrationTokenRequestEnums {

  type KeyType = KeyType.Value
  object KeyType extends Enumeration {
    val GUID = Value("GUID")
    val TELETAN = Value("TELETAN")
  }

}
