/**
 * cwa-verification-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.cwa.model


  /**
   * The test result model.
   */
case class TestResult(
  testResult: Option[Int] = None,
  sc: Option[Long] = None,
  labId: Option[String] = None,
  responsePadding: Option[String] = None
)

