/**
 * REST countries API
 * REST countries API
 *
 * The version of the OpenAPI document: v2.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.restcountries.model


case class CurrenciesV2(
  code: Option[String] = None,
  name: Option[String] = None,
  symbol: Option[String] = None
)

