/**
 * REST countries API
 * REST countries API
 *
 * The version of the OpenAPI document: v2.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.restcountries.model


case class LanguagesV2(
  iso639_1: Option[String] = None,
  iso639_2: Option[String] = None,
  name: Option[String] = None,
  nativeName: Option[String] = None
)

