/**
 * Common CRUD API
 *     A complete user registry, with access permissions,     JWT token, integration and unit tests, using     the RESTful API pattern. 
 *
 * The version of the OpenAPI document: v4.0.1
 * Contact: throyer.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.usersregistry.api

import examples.usersregistry.model.ApiError
import examples.usersregistry.model.Role
import examples.usersregistry.model.ValidationError
import examples.usersregistry.core.JsonSupport._
import sttp.client3._
import sttp.model.Method

object RolesApi {

def apply(baseUrl: String = "http://localhost:8080") = new RolesApi(baseUrl)
}

class RolesApi(baseUrl: String) {

  /**
   * Expected answers:
   *   code 400 : Seq[ValidationError] (Bad Request)
   *   code 401 : ApiError (Unauthorized)
   *   code 200 : Seq[Role] (OK)
   * 
   * Available security schemes:
   *   token (http)
   */
  def index1(bearerToken: String, 
): Request[Either[ResponseException[String, Exception], Seq[Role]], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/roles")
      .contentType("application/json")
      .auth.bearer(bearerToken)
      .response(asJson[Seq[Role]])

}
