/**
 * Bing Maps Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.bingmaps.model


case class ImageryResources(
  __type: Option[String] = None,
  imageHeight: Option[Int] = None,
  imageUrl: Option[String] = None,
  imageUrlSubdomains: Option[Seq[String]] = None,
  imageWidth: Option[Int] = None,
  zoomMax: Option[Int] = None,
  zoomMin: Option[Int] = None
)

