openapi: 3.0.0
servers:
  - url: 'http://localhost:8080/rest'
info:
  description: 'REST countries API'
  title: REST countries API
  version: v2.0.5
paths:
  /v1/all:
    get:
      operationId: v1All
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountriesV1'
  /v1/alpha/{alphacode}:
    get:
      operationId: v1Alphacode
      parameters:
        - name: alphacode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v1/alpha:
    get:
      operationId: v1Alphacodes
      parameters:
        - name: codes
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v1/currency/{currency}:
    get:
      operationId: v1Currency
      parameters:
        - name: currency
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v1/name/{name}:
    get:
      operationId: v1Name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
        - name: fullText
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v1/callingcode/{callingcode}:
    get:
      operationId: v1Callingcode
      parameters:
        - name: callingcode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v1/capital/{capital}:
    get:
      operationId: v1Capital
      parameters:
        - name: capital
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v1/region/{region}:
    get:
      operationId: v1Region
      parameters:
        - name: region
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v1/subregion/{subregion}:
    get:
      operationId: v1Subregion
      parameters:
        - name: subregion
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v1/lang/{lang}:
    get:
      operationId: v1Lang
      parameters:
        - name: lang
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/all:
    get:
      operationId: v2All
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountriesV2'
  /v2/alpha/{alphacode}:
    get:
      operationId: v2Alphacode
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
        - name: alphacode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/alpha:
    get:
      operationId: v2Alphacodes
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
        - name: codes
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/currency/{currency}:
    get:
      operationId: v2Currency
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
        - name: currency
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/name/{name}:
    get:
      operationId: v2Name
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
        - name: name
          in: path
          required: true
          schema:
            type: string
        - name: fullText
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/callingcode/{callingcode}:
    get:
      operationId: v2Callingcode
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
        - name: callingcode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/capital/{capital}:
    get:
      operationId: v2Capital
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
        - name: capital
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/region/{region}:
    get:
      operationId: v2Region
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
        - name: region
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/subregion/{subregion}:
    get:
      operationId: v2Subregion
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
        - name: subregion
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/lang/{lang}:
    get:
      operationId: v2Lang
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
        - name: lang
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/demonym/{demonym}:
    get:
      operationId: v2Demonym
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
        - name: demonym
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
  /v2/regionalbloc/{regionalbloc}:
    get:
      operationId: v2Regionalbloc
      parameters:
        - name: fields
          in: query
          required: false
          schema:
            type: string
        - name: regionalbloc
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        default:
          description: Other responses
components:
  schemas:
    CountriesV1:
      type: array
      items:
        $ref: '#/components/schemas/CountryV1'
    CountryV1:
      type: object
      properties:
        name:
          type: string
        alpha2Code:
          type: string
        alpha3Code:
          type: string
        callingCodes:
          type: array
          items:
            type: string
        capital:
          type: string
        currencies:
          type: array
          items:
            type: string
        languages:
          type: array
          items:
            type: string
        region:
          type: string
        subregion:
          type: string
    CountriesV2:
      type: array
      items:
        $ref: '#/components/schemas/CountryV2'
    CountryV2:
      type: object
      properties:
        name:
          type: string
        alpha2Code:
          type: string
        alpha3Code:
          type: string
        callingCodes:
          type: array
          items:
           type: string
        capital:
          type: string
        currencies:
          type: array
          items:
            $ref: '#/components/schemas/CurrenciesV2'
        languages:
          type: array
          items:
            $ref: '#/components/schemas/LanguagesV2'
        region:
          type: string
        subregion:
          type: string
        demonym:
          type: string
        regionalBlocs:
          type: array
          items:
            $ref: '#/components/schemas/RegionalBlocs'
    CurrenciesV2:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        symbol:
          type: string
    LanguagesV2:
      type: object
      properties:
        iso639_1:
          type: string
        iso639_2:
          type: string
        name:
          type: string
        nativeName:
          type: string
    RegionalBlocs:
      type: object
      properties:
        acronym:
          type: string
        name:
          type: string
        otherAcronyms:
          type: array
          items:
            type: string
        otherNames:
          type: array
          items:
            type: string