/**
 * User
 * Provide Customer login, register, retrieval, as well as card and address retrieval
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package examples.sockshop.model


case class Address(
  number: String,
  street: String,
  city: String,
  postcode: String,
  country: String,
  _links: AddressLinks
)

